name: climaax_flashflood

channels:
    - conda-forge

dependencies:
        - python=3.11
        - shapely
        - rasterio
        - rio-cogeo
        - matplotlib
        - pip
        - jupyterlab
        - ipywidgets
        - ipympl
        - pip:
            - damagescanner
            - jupyterlab_myst
