name: climaax_flashflood

channels:
    - conda-forge

dependencies:
        - python=3.11
        - gdal
        - xarray
        - cartopy
        - scipy
        - cdsapi
        - pip
        - plotly
        - pyproj
        - rioxarray        
        - matplotlib
        - dask
        - leafmap
        - jupyter-server-proxy
        - localtileserver
        - pip:
            - netcdf4
