name: climaax_flashflood

channels:
    - conda-forge

dependencies:
        - python=3.11
        - gdal
        - pip
        - jupyterlab
        - ipywidgets
        - leafmap
        - pip:
            - damagescanner
            - jupyterlab_myst
            - localtileserver[colormaps,jupyter,helpers]==0.7.2
            - shapely
            - rasterio
            - rio-cogeo
