name: climaax_flashflood

channels:
    - conda-forge

dependencies:
        - python=3.11
        - gdal
        - pip
        - jupyterlab
        - ipywidgets
        - leafmap
        - netCDF4
        - dask
        - xarray
        - rioxarray
        - cartopy
        - scipy
        - rasterio
        - numpy
        - cdsapi
        - plotly
        - contextily
        - pip:
            - damagescanner
            - jupyterlab_myst
            - localtileserver[colormaps,jupyter,helpers]==0.7.2
            - shapely
            - rio-cogeo
