name: climaax_flashflood

channels:
    - conda-forge

dependencies:
        - python=3.11
        - xarray
        - cartopy
        - cdsapi
        - pip
        - plotly
        - pyproj
        - matplotlib
        - pip:
            - netcdf4
